---
  - name: Install DBATools PowerShell module
    win_shell: Install-Module -Name dbatools -Force -Scope CurrentUser
    args:
      executable: powershell.exe
    when: inventory_hostname == 'sqltest'

  - name: Import DBATools module
    win_shell: Import-Module dbatools
    args:
      executable: powershell.exe
    when: inventory_hostname == 'sqltest'

  - name: Create list of script names
    ansible.windows.win_find:
      paths: "{{ bak_path }}"
      patterns: "{{ file_pattern }}"
      hidden: true
      recurse: true
    when: inventory_hostname == 'sqltest'
    delegate_to: sqltest
    register: bak_files
    notify: DBScripts List

  - name: Define Variables
    set_fact:
      sql_server_instance: "{{ restore_server }}\\localhost"
    when: inventory_hostname == 'sqltest'

  - name: Restore Databases
    win_shell: |
      $backupFolder = "{{ bak_path }}"
      $sqlServerInstance = "{{ sql_server_instance }}"
      $databasesToRestore = {{ bak_files.files map(attribute='filename') | list | to_json }}
      $databasesToRestore = $databasesToRestore | ConvertFrom-Json
      foreach ($database in $databasesToRestore) {
          Restore-DbaDatabase -Path "$backupFolder\\$database.filename" -SqlInstance $sqlServerInstance -Database $database
      }
    args:
      executable: powershell.exe
    when: inventory_hostname == 'sqltest'
    notify: Restore Executed
  
  - name: Remove Backup Folder
    win_shell: Remove-Item -Path "{{ bak_path }}" -Recurse -Force
    args:
      executable: powershell.exe
    notify: Remove BackUpFolder
    

