---
  - name: Install DBATools PowerShell module
    win_shell: Install-Module -Name dbatools -Force -Scope CurrentUser
    args:
      executable: powershell.exe
    when: inventory_hostname == 'sqltest'

  - name: Import DBATools module
    win_shell: Import-Module dbatools
    args:
      executable: powershell.exe
    when: inventory_hostname == 'sqltest'

  - name: Create list of script names
    ansible.windows.win_find:
      paths: "{{ bak_path }}"
      patterns: "{{ file_pattern }}"
      hidden: true
      recurse: true
    when: inventory_hostname == 'sqltest'
    delegate_to: sqltest
    register: bak_files
    notify: DBScripts List

  - name: Define Variables
    set_fact:
      sql_server_instance: "{{ restore_server }}\\localhost"
    when: inventory_hostname == 'sqltest'

  - name: Restore Databases
    community.general.dbatools_restore:
      sql_instance: "{{ sql_server_instance }}"
      database: "{{ item.filename | regex_replace('_(\\d{8})\\.BAK$', '') }}"  # Extract database name from filename
      source: "{{ bak_path }}/{{ item.filename }}"
    loop: "{{ bak_files.files }}"
    when: inventory_hostname == 'sqltest'
    notify: Restore Executed
  
  - name: Remove Backup Folder
    win_file:
      path: "{{ bak_path }}"
      state: absent
    when: inventory_hostname == 'sqltest'
    notify: Remove BackUpFolder
    

